#- hosts: centos
#  gather_facts: yes
#  become: false
#  tasks:
#  - name: Distribution
#    debug: msg="{{ ansible_distribution }}"
#  - name: Distribution version
#    debug: msg="{{ ansible_distribution_version}}"
#  - name: Distribution major version
#    debug: msg="{{ ansible_distribution_major_version }}"

# copy_file.yml
- name: copy files to destination
  hosts: centos
  tasks:
    - name: copy src.txt as dest.txt in the same dir 
      copy:
        src: /home/jh4cky/Lavoro/Doc/Ansible/pippo.txt
        dest: /tmp/centos7.txt
      when: ansible_distribution_major_version == '7'
