# copy_file.yml
#- name: copy files to destination
#  hosts: centos
#  tasks:
#    - name: copy src.txt as dest.txt in the same dir 
#      copy:
#        src: pippo.txt
#        dest: /tmp/pippo.txt


#- name: all
#  gather_facts: yes
#  hosts: centos
#  tasks:
#    - name: Check Dist Version
#      shell: cat /etc/os-release
#      register: response
#    - debug: msg="{{ response.stdout }}"



- hosts: centos
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"



