- hosts: centos
  gather_facts: yes
  become: false
  tasks:
  - name: Check global ports
    wait_for:
      host: "localhost"
      port: "224"
      state: started         # Port should be open
      delay: 0               # No wait before first check (sec)
      timeout: 3             # Stop checking after timeout (sec)
